# Machine Learning

##Pipeline
1. get data
2. extract feature
3. train model
4. test model
5. deploy model

In [ ]:
!pip install botnoi==0.2.1

     |████████████████████████████████| 16.0MB 217kB/s 


In [ ]:
import botnoi as bn

In [ ]:
im = bn.cv.image('https://ichef.bbci.co.uk/news/800/cpsprodpb/51F3/production/_106997902_gettyimages-611696954.jpg')

In [ ]:
im.getresnet50()

94773248/94765736 [==============================] - 0s 0us/step


array([0., 0., 0., ..., 0., 0., 0.])

In [ ]:
import pickle
imo = pickle.load(open('1.p','rb'))

array([0., 0., 0., ..., 0., 0., 0.])

In [ ]:
im.getresnet50()

94773248/94765736 [==============================] - 1s 0us/step


array([0., 0., 0., ..., 0., 0., 0.])

In [ ]:
im.getmobilenet()

17227776/17225924 [==============================] - 0s 0us/step


array([5.86987449e-06, 2.20390024e-04, 1.83721913e-06, 4.98189906e-07,
       9.57768370e-07, 3.95857888e-05, 1.69506346e-04, 2.82125294e-05,
       5.24540590e-05, 1.59861313e-05, 3.80317044e-06, 5.02670547e-06,
       2.59278623e-07, 4.04073918e-06, 6.32352943e-07, 4.21958982e-06,
       6.19289705e-06, 3.35838040e-06, 2.92574421e-06, 7.57527743e-07,
       1.55934297e-07, 2.11129323e-06, 2.14059569e-06, 3.67787764e-07,
       1.39340857e-05, 6.36865692e-06, 1.34153283e-07, 1.68942687e-07,
       5.05933689e-06, 3.89816581e-07, 2.01688519e-07, 4.44878072e-07,
       1.07575775e-08, 5.90210317e-07, 1.17914307e-06, 3.27033469e-06,
       5.15278059e-06, 3.59452877e-06, 6.35346071e-06, 2.65051720e-08,
       1.07268488e-07, 2.68899685e-07, 1.77594876e-06, 1.62349339e-05,
       5.42563239e-07, 1.87540345e-06, 5.12898242e-08, 3.50188944e-07,
       1.44030569e-06, 1.67701920e-08, 4.80967357e-07, 7.16928729e-06,
       1.35964276e-06, 9.34922052e-06, 3.94799604e-05, 1.18310905e-06,
      

In [ ]:
im.mobilenet

array([5.86987449e-06, 2.20390024e-04, 1.83721913e-06, 4.98189906e-07,
       9.57768370e-07, 3.95857888e-05, 1.69506346e-04, 2.82125294e-05,
       5.24540590e-05, 1.59861313e-05, 3.80317044e-06, 5.02670547e-06,
       2.59278623e-07, 4.04073918e-06, 6.32352943e-07, 4.21958982e-06,
       6.19289705e-06, 3.35838040e-06, 2.92574421e-06, 7.57527743e-07,
       1.55934297e-07, 2.11129323e-06, 2.14059569e-06, 3.67787764e-07,
       1.39340857e-05, 6.36865692e-06, 1.34153283e-07, 1.68942687e-07,
       5.05933689e-06, 3.89816581e-07, 2.01688519e-07, 4.44878072e-07,
       1.07575775e-08, 5.90210317e-07, 1.17914307e-06, 3.27033469e-06,
       5.15278059e-06, 3.59452877e-06, 6.35346071e-06, 2.65051720e-08,
       1.07268488e-07, 2.68899685e-07, 1.77594876e-06, 1.62349339e-05,
       5.42563239e-07, 1.87540345e-06, 5.12898242e-08, 3.50188944e-07,
       1.44030569e-06, 1.67701920e-08, 4.80967357e-07, 7.16928729e-06,
       1.35964276e-06, 9.34922052e-06, 3.94799604e-05, 1.18310905e-06,
      

In [ ]:
from botnoi import scrape as sc
from botnoi import cv
import os

In [ ]:
imgList = sc.get_image_urls('แมวโกรธ',30)

complete: 0.00%
completed


In [ ]:
imgList

['https://img.lovepik.com/element/40112/9516.png_860.png',
 'https://cdn.pixabay.com/photo/2016/11/28/17/55/cat-1865546_960_720.jpg',
 'https://i.pinimg.com/736x/d0/55/9e/d0559e12375e532d67d429bfdb93b073.jpg',
 'https://www.catdumb.com/wp-content/uploads/2016/08/562dc82cd8e7b.jpg',
 'https://cdn6.aptoide.com/imgs/d/d/b/ddbd8d243579054340cb491449fe3b1f_screen.png',
 'https://i.ytimg.com/vi/pnOlvJcmuoQ/maxresdefault.jpg',
 'https://men.mthai.com/app/uploads/2017/05/page-30.jpg',
 'https://men.mthai.com/app/uploads/2017/05/angry-kittens-7-591aef38bedce__700.jpg',
 'https://us-fbcloud.net/wb/data/1119/1119046-img.tfe8mb.34jik.jpg',
 'https://www.catdumb.com/wp-content/uploads/2015/12/grumpy-cat-vs-bon-jovi-cat-1.jpg',
 'https://men.mthai.com/app/uploads/2017/05/worlds-angriest-cat-18-591c1de524fd8__700.jpg',
 'https://www.cat-slave.com/wp-content/uploads/2020/09/bfngdndfndfg.jpg',
 'https://prodigits.co.uk/thumbs/wallpapers/p2ls/animals/36/a1e32fff12642010.jpg',
 'https://cdn6.aptoide.com/

In [ ]:
import IPython
from google.colab import output
htmlimage = getthumbdisplay(imgList)
html = '''<style>
img {
  border: 1px solid #ddd; /* Gray border */
  border-radius: 4px;  /* Rounded border */
  padding: 5px; /* Some padding */
  width: 150px; /* Set a small width */
}

/* Add a hover effect (blue shadow) */
img:hover {
  box-shadow: 0 0 2px 1px rgba(0, 140, 186, 0.5);
}
</style>
<body>

%s

</body>'''%htmlimage
display(IPython.display.HTML(html))

In [ ]:
def gethtmlimage(imgurl):
  htmlTag = '''
  <a target="_blank" href="%s">
    <img src="%s" alt="Forest">
  </a>
  '''%(imgurl,imgurl)
  return htmlTag


In [ ]:
def getthumbdisplay(imgList):
  res = ''
  for img in imgList:
    res = res + gethtmlimage(img)
  return res


In [ ]:
gethtmlimage('https://static.siamsport.co.th/news/2020/02/23/news202002230543139.jpg')

'\n  <a target="_blank" href="https://static.siamsport.co.th/news/2020/02/23/news202002230543139.jpg">\n    <img src="https://static.siamsport.co.th/news/2020/02/23/news202002230543139.jpg" alt="Forest">\n  </a>\n  '

In [ ]:
def extractimagefeat(query):
  #create folder
  foldername = 'images/'+query
  isdir = os.path.isdir(foldername) 
  #check if folder exist
  if not isdir:
    #create directory
    os.makedirs(foldername)
  #get images from google search
  imglist = sc.get_image_urls(query,30)
  i = 1
  for img in imglist[0:30]:
    #extract image features from each images and save to files
    try:
      print(i)
      #create image path
      savepath = foldername + '/' + str(i)+'.p'
      a = cv.image(img)
      a.getresnet50()
      #a.getmobilenet()
      #a.getmobilenet()
      a.save(savepath)
      i = i + 1
    except:
      pass
  return 'complete'


In [ ]:
rm -rf images

In [ ]:
clsList = ['แมวยิ้ม','แมวโกรธ']
for c in clsList:
  extractimagefeat(c)

complete: 0.00%
completed
1
2
3
4
5
6
7
8
9
10
11
12
13
14
14
15
16
17
18
19
20
21
22
23
24
25
25
26
27
27
complete: 0.00%
completed
1
2
3
4
5
6
7
7
7
8
9
9
10
11
11
12
13
14
15
16
17
18
19
19
20
21
22
23
24
24


In [ ]:
extractimagefeat('ทุเรียน')

complete: 0.00%
completed
1
2
3
4
5
6
7
8
9
10
10
11
12
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28


'complete'

In [ ]:
extractimagefeat('ขนุน')

complete: 0.00%
completed
1
2
3
4
4
5
6
7
8
9
9
10
11
12
13
14
15
15
16
16
17
18
19
19
20
21
21
22
23
24


'complete'

In [ ]:
extractimagefeat('หมา')

complete: 0.00%
completed
1
2
3
4
5
5
6
7
8
9
10
11
12
13
14
15
16
17
17
17
18
19
20
21
22
23
24
25
26
27


'complete'

In [ ]:
#command to clear or files
#rm -rf *

In [ ]:
import pickle
filename = 'images/รถกระบะ/1.p'
imo = pickle.load(open(filename,'rb'))

array([3.11183023e-06, 5.51758456e-06, 5.92193430e-07, 5.51873933e-07,
       5.49454860e-06, 4.14671353e-07, 2.05264982e-06, 2.35553901e-08,
       6.27730491e-08, 3.29042627e-08, 5.40216879e-07, 1.38635407e-06,
       2.14442352e-08, 1.72236751e-07, 2.98332112e-07, 1.28511382e-07,
       7.46722469e-07, 7.61752354e-07, 3.63121059e-08, 1.42009964e-08,
       1.93543794e-08, 1.16762311e-06, 4.24957033e-07, 3.96332104e-07,
       1.01854190e-07, 4.23712058e-06, 2.08705013e-07, 6.53953009e-07,
       2.13229582e-06, 2.21757001e-07, 6.88086765e-07, 1.07305010e-04,
       2.79353029e-07, 5.34894356e-06, 2.95622440e-06, 3.14253874e-08,
       8.29979724e-06, 4.92235297e-07, 6.20465530e-05, 1.74213363e-05,
       8.66236370e-05, 8.14979169e-07, 1.22109863e-06, 1.12178819e-07,
       6.04099514e-06, 6.91173369e-05, 1.37685753e-05, 5.07670762e-05,
       3.52526298e-05, 9.88770642e-08, 2.27460073e-07, 7.33548245e-05,
       4.51838402e-07, 3.88601146e-07, 7.91249561e-08, 1.61214320e-03,
      

In [ ]:
import glob
import pandas as pd
import pickle
def createdataset():
  imgfolder = glob.glob('images/*')
  dataset = []
  for cls in imgfolder:
    clsset = pd.DataFrame()
    pList = glob.glob(cls+'/*')
    featvec = []
    for p in pList:
      dat = pickle.load(open(p,'rb'))
      featvec.append(dat.resnet50)
      #featvec.append(dat.mobilenet)

    clsset['feature'] = featvec
    cls = cls.split('/')[-1]
    clsset['label'] = cls
    dataset.append(clsset)
  return pd.concat(dataset,axis=0)

In [ ]:
glob.glob('images/รถตู้/*')

['images/รถตู้/19.p',
 'images/รถตู้/4.p',
 'images/รถตู้/16.p',
 'images/รถตู้/22.p',
 'images/รถตู้/2.p',
 'images/รถตู้/13.p',
 'images/รถตู้/8.p',
 'images/รถตู้/15.p',
 'images/รถตู้/3.p',
 'images/รถตู้/9.p',
 'images/รถตู้/23.p',
 'images/รถตู้/24.p',
 'images/รถตู้/21.p',
 'images/รถตู้/11.p',
 'images/รถตู้/7.p',
 'images/รถตู้/6.p',
 'images/รถตู้/12.p',
 'images/รถตู้/5.p',
 'images/รถตู้/17.p',
 'images/รถตู้/20.p',
 'images/รถตู้/10.p',
 'images/รถตู้/18.p',
 'images/รถตู้/14.p',
 'images/รถตู้/1.p']

In [ ]:
dataset = createdataset()

In [ ]:
dataset

feature    label
0   [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  แมวโกรธ
1   [0.0, 0.0, 0.0, 0.006128407995333864, 0.0, 0.0...  แมวโกรธ
2   [0.0, 0.0, 0.0, 0.0016199074494330163, 0.0, 0....  แมวโกรธ
3   [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  แมวโกรธ
4   [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  แมวโกรธ
5   [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  แมวโกรธ
6   [0.0, 0.0005821458289579234, 0.0, 0.0047437885...  แมวโกรธ
7   [0.0, 0.0027308223082273464, 0.0, 0.0, 0.0, 0....  แมวโกรธ
8   [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  แมวโกรธ
9   [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  แมวโกรธ
10  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0080194827989...  แมวโกรธ
11  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  แมวโกรธ
12  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  แมวโกรธ
13  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  แมวโกรธ
14  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  แมวโกรธ
15  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  แมวโกรธ
16  [0.0, 0.0, 0.0, 0.005534816476736478, 0.0, 0.0...  แมวโกรธ
17  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  แมวโกรธ
18  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  แมวโกรธ
19  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  แมวโกรธ
20  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0010357681746...  แมวโกรธ
21  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.004...  แมวโกรธ
22  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  แมวโกรธ
23  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  แมวโกรธ
0   [0.0, 0.00034355072627659114, 0.0, 0.0, 0.0, 0...  แมวยิ้ม
1   [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  แมวยิ้ม
2   [0.0, 0.0, 0.0024646126392952965, 0.0, 0.0, 0....  แมวยิ้ม
3   [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  แมวยิ้ม
4   [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  แมวยิ้ม
5   [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  แมวยิ้ม
6   [0.0, 0.0, 0.0, 0.0016663439355840831, 0.00024...  แมวยิ้ม
7   [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  แมวยิ้ม
8   [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  แมวยิ้ม
9   [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  แมวยิ้ม
10  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0036417940481...  แมวยิ้ม
11  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  แมวยิ้ม
12  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  แมวยิ้ม
13  [0.0, 0.0, 0.0, 0.003792883409763515, 0.0, 0.0...  แมวยิ้ม
14  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  แมวยิ้ม
15  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  แมวยิ้ม
16  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  แมวยิ้ม
17  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  แมวยิ้ม
18  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  แมวยิ้ม
19  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  แมวยิ้ม
20  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  แมวยิ้ม
21  [0.0, 0.0, 0.0, 0.0018407369581406588, 0.0, 0....  แมวยิ้ม
22  [0.0008104856381452369, 0.0, 0.003192551193439...  แมวยิ้ม
23  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.000...  แมวยิ้ม
24  [0.0, 0.0, 0.0003676578177202439, 0.0006542540...  แมวยิ้ม
25  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  แมวยิ้ม
26  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  แมวยิ้ม

## Train model

In [ ]:
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.svm import LinearSVC
def trainmodel(dataset,modfile=''):
  trainfeat, testfeat, trainlabel, testlabel = train_test_split(dataset['feature'], dataset['label'], test_size=0.20, random_state=0)
  clf = LinearSVC()
  mod = clf.fit(np.vstack(trainfeat.values),trainlabel.values)
  res = mod.predict(np.vstack(testfeat.values))
  if modfile!='':
    pickle.dump(mod,open(modfile,'wb'))
  acc = sum(res == testlabel)/len(res)
  return mod,acc

In [ ]:
mod,acc = trainmodel(dataset,'mymod.mod')

In [ ]:
acc

0.45454545454545453

In [ ]:
# output function
modFile = 'mymod.mod'
mod = pickle.load(open(modFile,'rb'))

In [ ]:
def predicting(imgurl):
  a = cv.image(imgurl)
  feat = a.getresnet50()
  res = mod.predict([feat])
  return res

In [ ]:
a=predicting('https://pbs.twimg.com/media/DnwiLohUcAADcIB.jpg')
# a=predictimg('https://f.ptcdn.info/810/034/000/1440553775-IMG5594-o.jpg')
a

array(['แมวยิ้ม'], dtype=object)